---
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - prettier
plugins:
  - node
  - prettier
rules:
  prettier/prettier: error
  block-scoped-var: warn
  eqeqeq: error
  no-warning-comments: warn
  no-unsafe-finally: warn
  node/no-deprecated-api: warn
  node/no-missing-require: warn
